# Generated by Django 5.2.4 on 2026-01-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('verified', 'VERIFIED'), ('rejected', 'REJECTED'), ('resolved', 'RESOLVED'), ('escalated', 'ESCALATED'), ('archived', 'ARCHIVED')], default='pending', max_length=20),
        ),
    ]
