# Generated by Codex on 2026-02-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='openrouter', max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=150)),
                ('prompt_redacted', models.TextField()),
                ('response_text', models.TextField()),
                ('explainability', models.JSONField(blank=True, default=dict)),
                ('confidence_label', models.CharField(blank=True, max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_interaction_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
