# Generated by Django 5.2.4 on 2026-02-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_aiinteractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('supervisor', 'Supervisor'), ('analyst', 'Analyst'), ('officer', 'Field Officer'), ('public', 'Public User')], default='public', max_length=20),
        ),
    ]
