# Generated by Django 5.2.4 on 2026-03-05 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_auditlog_hash_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_events', to='infrastructure.eventmodel'),
        ),
    ]
