# Generated by Django 5.2.4 on 2026-03-05 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_event_status_history(apps, schema_editor):
    EventModel = apps.get_model('infrastructure', 'EventModel')
    EventStatusHistory = apps.get_model('infrastructure', 'EventStatusHistory')

    for event in EventModel.objects.all().iterator():
        if EventStatusHistory.objects.filter(event_id=event.id).exists():
            continue
        EventStatusHistory.objects.create(
            event_id=event.id,
            from_status='',
            to_status=event.status,
            reason='Initial history backfilled during enterprise migration',
            metadata={'backfilled': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_eventmodel_parent_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_status_history',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflictLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(db_index=True, max_length=50)),
                ('record_id', models.CharField(db_index=True, max_length=64)),
                ('client_version', models.PositiveIntegerField()),
                ('server_version', models.PositiveIntegerField()),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sync_conflict_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='source_form_version_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='source_record_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='source_record_type',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='source_system',
            field=models.CharField(db_index=True, default='sentinel', max_length=50),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='eventmodel',
            index=models.Index(fields=['source_system', 'source_record_type'], name='events_source_idx'),
        ),
        migrations.AddField(
            model_name='eventstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventstatushistory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='infrastructure.eventmodel'),
        ),
        migrations.AddField(
            model_name='syncconflictlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_event_status_history, migrations.RunPython.noop),
    ]
