# Generated by Django 5.2.4 on 2026-01-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inehss', '0001_initial'),
        ('infrastructure', '0004_alter_eventmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='event_category',
            field=models.CharField(default='environmental_hazard', help_text='Category for events created from this form', max_length=100),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='map_color',
            field=models.CharField(default='#f97316', help_text='Hex color for map markers', max_length=20),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='map_icon',
            field=models.CharField(default='warning', help_text='Icon name for map markers (e.g., warning, alert, biohazard)', max_length=50),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_reports', to='infrastructure.eventmodel'),
        ),
    ]
