# Generated by Django 5.2.4 on 2026-02-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inehss', '0002_formtemplate_event_category_formtemplate_map_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerassignment',
            name='is_persistent',
            field=models.BooleanField(default=False, help_text='If true, assignment remains open for multiple submissions (Patrol Mode)'),
        ),
        migrations.AlterField(
            model_name='officerassignment',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inehss.hazardreport'),
        ),
    ]
