# Generated by Django 5.2.4 on 2026-03-05 03:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inehss', '0005_formsubmission_location_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='geo_mode',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('manual', 'Manual Entry'), ('auto', 'Automatic GPS')], default='manual', help_text='Strategy for capturing geolocation', max_length=20),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='parent_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_reports', to='inehss.hazardreport'),
        ),
        migrations.AlterField(
            model_name='hazardreport',
            name='form_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_legacy', to='inehss.formtemplate'),
        ),
        migrations.AlterField(
            model_name='officerassignment',
            name='inspection_form',
            field=models.ForeignKey(blank=True, limit_choices_to={'form_type': 'officer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_legacy', to='inehss.formtemplate'),
        ),
        migrations.CreateModel(
            name='FormVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('schema', models.JSONField(default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='inehss.formtemplate')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='form_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='inehss.formversion'),
        ),
        migrations.AddField(
            model_name='officerassignment',
            name='form_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inehss.formversion'),
        ),
    ]
