# Generated by Django 5.2.4 on 2026-03-05 03:53

from django.db import migrations


def migrate_to_versions(apps, schema_editor):
    FormTemplate = apps.get_model('inehss', 'FormTemplate')
    FormVersion = apps.get_model('inehss', 'FormVersion')
    HazardReport = apps.get_model('inehss', 'HazardReport')
    OfficerAssignment = apps.get_model('inehss', 'OfficerAssignment')

    # 1. Create FormVersions for existing templates
    for template in FormTemplate.objects.all():
        version = FormVersion.objects.create(
            template=template,
            version_number=1,
            schema=template.schema,
            is_published=True
        )
        
        # 2. Update existing HazardReports
        HazardReport.objects.filter(form_template=template).update(form_version=version)

        # 3. Update existing OfficerAssignments
        OfficerAssignment.objects.filter(inspection_form=template).update(form_version=version)

def revert_versions(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inehss', '0006_formtemplate_geo_mode_hazardreport_parent_report_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_to_versions, revert_versions),
    ]
