# Generated by Django 5.2.4 on 2026-03-05 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inehss', '0007_auto_20260305_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplate',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='hazardreport',
            name='form_template',
        ),
        migrations.RemoveField(
            model_name='officerassignment',
            name='inspection_form',
        ),
        migrations.AlterField(
            model_name='hazardreport',
            name='form_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='inehss.formversion'),
        ),
        migrations.AlterField(
            model_name='officerassignment',
            name='form_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inehss.formversion'),
        ),
    ]
