# Generated by Django 5.2.4 on 2026-03-05 23:09

import django.db.models.deletion
import json
import uuid
from django.conf import settings
from django.db import migrations, models


def _schema_field_key(field, fallback_index):
    raw_key = field.get('name') or field.get('key') or field.get('id') or f'field_{fallback_index}'
    return str(raw_key)


def _value_to_text(value):
    if value is None:
        return ''
    if isinstance(value, (dict, list)):
        return json.dumps(value, sort_keys=True, default=str)
    return str(value)


def backfill_enterprise_structures(apps, schema_editor):
    FormVersion = apps.get_model('inehss', 'FormVersion')
    FormFieldDefinition = apps.get_model('inehss', 'FormFieldDefinition')
    HazardReport = apps.get_model('inehss', 'HazardReport')
    HazardReportStatusHistory = apps.get_model('inehss', 'HazardReportStatusHistory')
    HazardReportValue = apps.get_model('inehss', 'HazardReportValue')
    OfficerAssignment = apps.get_model('inehss', 'OfficerAssignment')
    OfficerAssignmentStatusHistory = apps.get_model('inehss', 'OfficerAssignmentStatusHistory')
    FormSubmission = apps.get_model('inehss', 'FormSubmission')
    FormSubmissionValue = apps.get_model('inehss', 'FormSubmissionValue')
    EventModel = apps.get_model('infrastructure', 'EventModel')

    for form_version in FormVersion.objects.all().iterator():
        active_keys = []
        for index, field in enumerate(form_version.schema or [], start=1):
            if not isinstance(field, dict):
                continue
            field_key = _schema_field_key(field, index)
            FormFieldDefinition.objects.update_or_create(
                form_version_id=form_version.id,
                field_key=field_key,
                defaults={
                    'field_label': field.get('label') or field_key.replace('_', ' ').title(),
                    'field_type': str(field.get('type', 'text')),
                    'is_required': bool(field.get('required', False)),
                    'is_active': True,
                    'order_index': index,
                    'config': field,
                },
            )
            active_keys.append(field_key)

        if active_keys:
            FormFieldDefinition.objects.filter(form_version_id=form_version.id).exclude(field_key__in=active_keys).update(is_active=False)
        else:
            FormFieldDefinition.objects.filter(form_version_id=form_version.id).update(is_active=False)

    for report in HazardReport.objects.select_related('form_version').all().iterator():
        if not HazardReportStatusHistory.objects.filter(report_id=report.id).exists():
            HazardReportStatusHistory.objects.create(
                report_id=report.id,
                from_status='',
                to_status=report.status,
                reason='Initial history backfilled during enterprise migration',
                metadata={'backfilled': True},
            )

        field_definitions = {
            definition.field_key: definition
            for definition in FormFieldDefinition.objects.filter(form_version_id=report.form_version_id)
        }
        seen_ids = []
        for key, value in (report.data or {}).items():
            field_definition = field_definitions.get(str(key))
            if field_definition is None:
                field_definition = FormFieldDefinition.objects.create(
                    form_version_id=report.form_version_id,
                    field_key=str(key),
                    field_label=str(key).replace('_', ' ').title(),
                    field_type='unknown',
                    is_active=False,
                    order_index=len(field_definitions) + 1,
                    config={'auto_generated': True, 'backfilled': True},
                )
                field_definitions[field_definition.field_key] = field_definition

            HazardReportValue.objects.update_or_create(
                report_id=report.id,
                field_definition_id=field_definition.id,
                defaults={'value': value, 'value_text': _value_to_text(value)},
            )
            seen_ids.append(field_definition.id)

        if seen_ids:
            HazardReportValue.objects.filter(report_id=report.id).exclude(field_definition_id__in=seen_ids).delete()

        if report.event_id:
            EventModel.objects.filter(pk=report.event_id).update(
                source_system='inehss',
                source_record_type='hazard_report',
                source_record_id=str(report.id),
                source_form_version_id=report.form_version_id,
            )

    for assignment in OfficerAssignment.objects.all().iterator():
        if OfficerAssignmentStatusHistory.objects.filter(assignment_id=assignment.id).exists():
            continue
        OfficerAssignmentStatusHistory.objects.create(
            assignment_id=assignment.id,
            from_status='',
            to_status=assignment.status,
            reason='Initial history backfilled during enterprise migration',
            metadata={'backfilled': True},
        )

    for submission in FormSubmission.objects.select_related('assignment').all().iterator():
        field_definitions = {
            definition.field_key: definition
            for definition in FormFieldDefinition.objects.filter(form_version_id=submission.assignment.form_version_id)
        }
        seen_ids = []
        for key, value in (submission.data or {}).items():
            field_definition = field_definitions.get(str(key))
            if field_definition is None:
                field_definition = FormFieldDefinition.objects.create(
                    form_version_id=submission.assignment.form_version_id,
                    field_key=str(key),
                    field_label=str(key).replace('_', ' ').title(),
                    field_type='unknown',
                    is_active=False,
                    order_index=len(field_definitions) + 1,
                    config={'auto_generated': True, 'backfilled': True},
                )
                field_definitions[field_definition.field_key] = field_definition

            FormSubmissionValue.objects.update_or_create(
                submission_id=submission.id,
                field_definition_id=field_definition.id,
                defaults={'value': value, 'value_text': _value_to_text(value)},
            )
            seen_ids.append(field_definition.id)

        if seen_ids:
            FormSubmissionValue.objects.filter(submission_id=submission.id).exclude(field_definition_id__in=seen_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inehss', '0008_remove_formtemplate_schema_and_more'),
        ('infrastructure', '0010_eventstatushistory_syncconflictlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='officerassignment',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hazardreport',
            name='tracking_id',
            field=models.CharField(editable=False, max_length=24, unique=True),
        ),
        migrations.CreateModel(
            name='FormFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=150)),
                ('field_label', models.CharField(max_length=255)),
                ('field_type', models.CharField(default='text', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='inehss.formversion')),
            ],
            options={
                'ordering': ['order_index', 'field_label'],
                'unique_together': {('form_version', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='HazardReportStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_report_status_changes', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='inehss.hazardreport')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficerAssignmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='inehss.officerassignment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmissionValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('value_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_values', to='inehss.formfielddefinition')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='inehss.formsubmission')),
            ],
            options={
                'ordering': ['field_definition__order_index', 'field_definition__field_label'],
                'unique_together': {('submission', 'field_definition')},
            },
        ),
        migrations.CreateModel(
            name='HazardReportValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('value_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_values', to='inehss.formfielddefinition')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='inehss.hazardreport')),
            ],
            options={
                'ordering': ['field_definition__order_index', 'field_definition__field_label'],
                'unique_together': {('report', 'field_definition')},
            },
        ),
        migrations.RunPython(backfill_enterprise_structures, migrations.RunPython.noop),
    ]
