# Generated by Django 5.2.4 on 2026-03-06 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inehss', '0009_formsubmission_version_hazardreport_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreport',
            name='origin_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='inehss.officerassignment'),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='origin_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_report', to='inehss.formsubmission'),
        ),
    ]