# Generated by Django 5.2.4 on 2026-03-06 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inehss', '0010_hazardreport_patrol_lineage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='follow_up_for',
            field=models.ForeignKey(blank=True, help_text='Base form template that this officer form is designed to follow up on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_templates', to='inehss.formtemplate'),
        ),
    ]
